routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//--------- pages -------------
Route::get('/', [FrontController::class, 'index'])->name('home');
Route::get('/blog', [FrontController::class, 'blog'])->name('blog');
Route::get('/career', [FrontController::class, 'career'])->name('career');
Route::get('/contact', [FrontController::class, 'contact'])->name('contact');
Route::get('/feedback', [FrontController::class, 'feedback'])->name('feedback');


Route::prefix('/about')->group(function () {
    Route::get('/', [FrontController::class, 'about'])->name('about');
    Route::get( '/background', [FrontController::class, 'background'])->name('background');
    Route::get( '/vision-mission', [FrontController::class, 'vision_mission'])->name('vision-mission');
    Route::get( '/organisation-chart', [FrontController::class, 'organisation_chart'])->name('organisation-chart');

});

Route::prefix('/services')->group(function () {
    Route::get( '/', [FrontController::class, 'services'])->name('services');
    Route::get( '/product-certification', [FrontController::class, 'product_certification'])->name('product-certification');
    Route::get( '/local-product-listing', [FrontController::class, 'local_product_listing'])->name('local-product-listing');
    Route::get( '/testing-services', [FrontController::class, 'testing_services'])->name('testing_services');
    Route::get( '/directory', [FrontController::class, 'testing_services'])->name('testing_services');
    Route::get( '/guides', [FrontController::class, 'guides'])->name('guides');
});

//certification

Route::prefix('/certification')->group(function () {
    Route::get( '/products', [FrontController::class, 'certified_product'])->name('products');
    Route::get( '/standard', [FrontController::class, 'certified_standard'])->name('standard');
    Route::get( '/relevant-acts-directives', [FrontController::class, 'relevant_acts_directives'])->name('relevant-acts-directives');
    Route::get('certified_product_detail/{id}',[FrontController::class,'certified_product_detail'])->name('certified_product_detail');
});

//Forms

Route::prefix('/forms')->group(function () {
    Route::get( '/products', [FrontController::class, 'forms_product'])->name('products');
    Route::get( '/products-list', [FrontController::class, 'form_products_list'])->name('products-list');
    Route::get( '/consignments', [FrontController::class, 'form_consignments'])->name('consignments');

});


 //----- end pages ----------------------------------------------------------


Auth::routes();

Route::get('/admin', [HomeController::class, 'index'])->name('admin');



// admin routes
Route::group(['middleware' => 'App\Http\Middleware\IsAdmin'], function ()
{
    Route::get('admin/dashboard', [HomeController::class,'index']);


    Route::get('admin/form_list',[FormController::class,'form_list'])->name('admin.form_list');
    Route::resource('admin/form',FormController::class);

    Route::get('admin/certified_product_list',[ProductController::class,'certified_product_list'])->name('admin.certified_product_list');
    Route::resource('admin/certified_product',ProductController::class);



});

resources/views/Admin/certified_product_list.blade.php
@extends('Admin.layouts.master')

@section('content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>All Certified Products</h3>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->

                    <div class="card">

                        <div class="card-header">
                            <h3 class="card-title">


                                <a href="{{ url('admin/certified_product')}}" class="btn btn-block btn-success" onclick="">Add New product</a>


                            </h3>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped ">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Certificate Number</th>
                                    <th>Customer</th>
                                    <th>Product Standard</th>


                                    <th>Status</th>
                                    <th colspan="2">Action</th>


                                </tr>
                                </thead>
                                <tbody>
                                @foreach($table_data as $key => $value)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $value->name }}</td>
                                        <td>{{ $value->certificate_no }}</td>
                                        <td>{{ $value->customer->name }}</td>

                                        <td>{{ $value->std->name }}</td>


                                        <td>{{ $value->status ? 'Active' :'Pending'}}</td>
                                        <td><a href="{{url('admin/form/'.$value->id)}}"><i class="fa fa-edit"></i></a></td>
                                        <td><a class="btn btn-sm btn-outline-danger" onclick="shop_deactive({{$value->id}})"><i class="fa fa-trash" style="color: red"></i></a></td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>


@endsection

resources/views/Admin/form.blade.php
<!-- import header -->
@extends('Admin.layouts.master')
<!-- import header -->

@section('content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        &nbsp;
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Add Form</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">




                            @if($form == '')
                                @csrf
                                <form action="{{ url('admin/form') }}" method="post" enctype="multipart/form-data" >
                                    @else
                                        <form enctype="multipart/form-data" method="post" action="{{ url('admin/form/'.$form->id) }}">

                                            @csrf
                                            @method('PUT')


                                            @endif



                                            @include('Admin.layouts.errors')

                                            <div class="row">
                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label>Form Name</label>
                                                    <input type="text" class="form-control @error('name') is-invalid @enderror" required="" placeholder="Slider Name" name="name" value="{{ $form != ''? $form->name: old('name')}}">
                                                </div>

                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label>Form Code</label>
                                                    <input type="text" class="form-control @error('code') is-invalid @enderror" required="" placeholder="Slider Name" name="code" value="{{ $form != ''? $form->code: old('code')}}">
                                                </div>

                                                <div class="form-group  col-lg-6 col-md-6">
                                                    <label>Status</label>
                                                    <select class="form-control select2" name="status" style="width: 100%;">
                                                        <option value="1">Active</option>
                                                        <option value="0">Inactive</option>
                                                    </select>
                                                </div>

                                                <div class="form-group  col-lg-6 col-md-6">
                                                    <div class="form-group">
                                                        <input type="hidden" name="url" value="{{ $form != ''? $form->url: old('url')}}">
                                                        <input type="file" name="file"  placeholder="Choose file" id="file" value="{{ $form != ''? $form->url: old('url')}}">

                                                    </div>
                                                </div>


                                                <div class="form-group col-lg-6 col-md-6">
                                                    <label>Form Type</label>
                                                    <select name="type" class="form-control">
                                                        <option value="1" {{ ($form != '' && $form->type == "1")? "selected": "" }}>Product Certification</option>
                                                        <option value="2" {{ ($form != '' && $form->type == "2")? "selected": "" }}>Product Listing</option>
                                                        <option value="3" {{ ($form != '' && $form->type == "3")? "selected": "" }}>Testing Services</option>
                                                        <option value="4" {{ ($form != '' && $form->type == "4")? "selected": "" }}>Consignments</option>
                                                        <option value="4" {{ ($form != '' && $form->type == "5")? "selected": "" }}>Fees</option>
                                                    </select>
                                                </div>

                                            </div>


                                            <div class="form-group">
                                                <label>Description</label>

                                                   <textarea type="text"  class="form-control textarea    " id="description" name="description" @if($form==null) value=""  @else value=" {{$form->description}}" @endif  ></textarea>

                                                  </div>






                                            <div class="form-group">
                                                <button type="submit" class="btn btn-lg btn-dark rounded px-5">Submit</button>
                                            </div>
                                        </form>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div>

    <div id="uploadimageModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Crop Image</h4>
                </div>
                <div class="modal-body">
                    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
                        <div>
                            <div id="upload-demo"></div>
                            <input type="hidden" id="model_id">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="upload-image" class="btn btn-primary">Crop</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>

@endsection

resources/views/Admin/form_list.blade.php
@extends('Admin.layouts.master')

@section('content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>All Promotions</h3>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->

                    <div class="card">

                        <div class="card-header">
                            <h3 class="card-title">


                                <a href="{{ url('admin/form')}}" class="btn btn-block btn-success" onclick="">Add New Form</a>


                            </h3>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped ">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Code</th>
                                    <th>Type</th>
                                    <th>Path</th>
                                    <th>Status </th>
                                    <th colspan="2">Action</th>


                                </tr>
                                </thead>
                                <tbody>
                                @foreach($table_data as $key => $value)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $value->name }}</td>
                                        <td>{{ $value->code }}</td>
                                        <td>{{ $value->type }}</td>
                                        <td>{{ $value->url }}</td>


                                        <td>{{ $value->status ? 'Active' :'Pending'}}</td>
                                        <td><a href="{{url('admin/form/'.$value->id)}}"><i class="fa fa-edit"></i></a> </td>
                                        <td><a class="btn btn-sm btn-outline-danger" onclick="shop_deactive({{$value->id}})"><i class="fa fa-trash" style="color: red"></i></a></td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>


@endsection

resources/views/Admin/product.blade.php
<!-- import header -->
@extends('Admin.layouts.master')
<!-- import header -->

@section('content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        &nbsp;
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Add Certified Product</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">


                            @if($form == null)

                                <form action="{{ route('certified_product.store') }}" method="post" enctype="multipart/form-data">
                                    @else
                                        <form enctype="multipart/form-data" method="post" action="{{ route('certified_product.update' ) }}">


                                            @endif

                                            @csrf

                                            @include('Admin.layouts.errors')

                                            <div class="row">
                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label>Name</label>
                                                    <input type="text" class="form-control @error('name') is-invalid @enderror" required="" placeholder="certified product Name" name="name"
                                                           value="{{ $form != ''? $form->name: old('name')}}">
                                                </div>

                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label>Certificate Number</label>
                                                    <input type="text" class="form-control @error('certificate_no') is-invalid @enderror" required="" placeholder="Certificate Number" name="certificate_no"
                                                           value="{{ $form != ''? $form->certificate_no: old('certificate_no')}}">
                                                </div>

                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label>Listing number</label>
                                                    <input type="text" class="form-control @error('listing_no') is-invalid @enderror" required="" placeholder="listing number" name="listing_no"
                                                           value="{{ $form != ''? $form->listing_no: old('listing_no')}}">
                                                </div>

                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label for="customer_id">Customer</label>
                                                    <select class="form-control" name="customer_id" id="customer_id">
                                                        @foreach($customer as $customer_select)
                                                            <option value="{{$customer_select->id}}">{{$customer_select->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>



                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label for="customer_id">Country Of Origin</label>
                                                    <select class="form-control" name="country" id="country">
                                                        @foreach($origin as $country_select)
                                                            <option value="{{$country_select->id}}">{{$country_select->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>


                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label for="customer_id">Standard</label>
                                                    <select class="form-control" name="standard" id="standard">
                                                        @foreach($standard as $standard_select)
                                                            <option value="{{$standard_select->id}}">{{$standard_select->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>




                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label>Expire Date</label>
                                                    <input type="date" class="form-control @error('expiry_date') is-invalid @enderror" required="" placeholder="Listing NUmber" name="expiry_date"
                                                           value="{{ $form != ''? $form->expiry_date: old('expiry_date')}}">
                                                </div>


                                                <div class="form-group     col-lg-6 col-md-6">
                                                    <label for="brand">Brands</label>
                                                    <select class="form-control" name="brand_id" id="brand_id">
                                                        @foreach($brand as $brand_select)
                                                            <option value="{{$brand_select->id}}">{{$brand_select->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>


                                                <div class="form-group  col-lg-6 col-md-6">
                                                    <label>Status</label>
                                                    <select class="form-control select2" name="status" style="width: 100%;">
                                                        <option value="1">Active</option>
                                                        <option value="0">Inactive</option>
                                                    </select>
                                                </div>


                                            </div>




                                            <div class="form-group">
                                                <label>Description</label>

                                                <textarea type="text" class="form-control textarea    " id="description" name="description" @if($form==null) value=""
                                                          @else value=" {{$form->description}}" @endif  ></textarea>

                                            </div>


                                            <div class="form-group">
                                                <button type="submit" class="btn btn-lg btn-dark rounded px-5">Submit</button>
                                            </div>
                                        </form>
                                </form>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
    </div>

    <div id="uploadimageModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Crop Image</h4>
                </div>
                <div class="modal-body">
                    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
                        <div>
                            <div id="upload-demo"></div>
                            <input type="hidden" id="model_id">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="upload-image" class="btn btn-primary">Crop</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>

@endsection

resources/views/Admin/standard_list.blade.php
@extends('Admin.layouts.master')

@section('content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>All Certified Products</h3>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->

                    <div class="card">

                        <div class="card-header">
                            <h3 class="card-title">


                                <a href="{{ url('admin/certified_product')}}" class="btn btn-block btn-success" onclick="">Add New product</a>


                            </h3>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped ">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Certificate Number</th>
                                    <th>Customer</th>
                                    <th>Product Standard</th>


                                    <th>Status </th>
                                    <th colspan="2">Action</th>


                                </tr>
                                </thead>
                                <tbody>
                                @foreach($table_data as $key => $value)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $value->holder() }}</td>
                                        <td>{{ $value->customer_id }}</td>
                                        <td>{{ $value->standard }}</td>



                                        <td>{{ $value->status ? 'Active' :'Pending'}}</td>
                                        <td><a href="{{url('admin/form/'.$value->id)}}"><i class="fa fa-edit"></i></a> </td>
                                        <td><a class="btn btn-sm btn-outline-danger" onclick="shop_deactive({{$value->id}})"><i class="fa fa-trash" style="color: red"></i></a></td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>


@endsection